openapi: 3.0.1
info:
  title: '@jupiterone/graph-jenkins'
  description: A JupiterOne Integration for ingesting data of Jenkins
  x-cortex-git:
    github:
      repository: JupiterOne/graph-jenkins
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-jenkins'
  x-cortex-service-groups:
    - tier-4
